### PR TITLE
Close #73: add Dockerfile

### LINKED ISSUE #73: Create Dockerfile
suggestion, create a Dockerfile for ease of configuration and testing.

### PR DESCRIPTION
**Pull request by Bedotech**
Fix default ip address to 0.0.0.0 for allow connection throught docker
containers.

@evilsocket if you have any suggestion i want to contribute in an effective way.

### CODE REVIEW

**Comment by evilsocket** [comment]
The default ip address **does not need to be fixed**, it's default'ed to `127.0.0.1` for security reasons, I can't merge this PR as long as you don't use your own config.json instead of "fixing" the example one.

As per contributing in effective ways, [here you go](https://github.com/evilsocket/arc/issues) :)

**Comment by evilsocket** [comment]
Maybe a solution can be to have a dedicated JSON config file for docker? Just `docker_config.json` maybe?

**Comment by Bedotech** [comment]
yeah i choose the second, in docker container it's really unnecessary bind to local interface. another approach can be override default config value via environment variable, what you prefer?

**Comment by evilsocket** [comment]
As I said, I prefer another configuration file specific for docker.

**Pull request merged**
